import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { prisma, logSection, logCount } from "../client";

/**
 * Categories + structured positions — assigns a therapeutic-exercise category
 * and fills startPosition / endPosition / rom for every exercise, from data
 * generated by the categorize-and-positions workflow. Category is always set;
 * position fields fill only when empty (never clobbers human-authored text).
 * Data lives in the sibling JSON so it is reproducible.
 */

const FILE = join(__dirname, "categories-positions-2026-07.json");
const CATEGORIES = new Set(["strength", "stretch", "mobility", "balance", "motor-control", "breathwork", "aerobic", "sensory", "functional"]);

export async function seedCategoriesPositionsExtension() {
  logSection("Categories + structured positions");
  if (!existsSync(FILE)) { console.log("    (no categories/positions JSON — skipping)"); return; }

  const items: any[] = JSON.parse(readFileSync(FILE, "utf8"));
  let n = 0;
  for (const it of items) {
    const ex = await prisma.exercise.findUnique({ where: { slug: it.slug }, select: { id: true, startPosition: true, endPosition: true, rom: true } });
    if (!ex) continue;
    const data: any = {};
    if (it.category && CATEGORIES.has(it.category)) data.category = it.category;
    if (it.startPosition && !ex.startPosition) data.startPosition = it.startPosition;
    if (it.endPosition && !ex.endPosition) data.endPosition = it.endPosition;
    if (it.rom && !ex.rom) data.rom = it.rom;
    if (Object.keys(data).length) { await prisma.exercise.update({ where: { id: ex.id }, data }); n++; }
  }
  logCount("exercises categorized + positioned", n);
}
