#!/usr/bin/env tsx
/**
 * Import evidence-based coaching-cue rewrites from literature-review responses.
 *
 * Reads `research/cues-batch-*-response.md` (gitignored) — the answers to the
 * prompts emitted by `pnpm cue:prompts` — parses the strict block format, and
 * CODEGENS a committed seed extension at `prisma/seed/extensions/cue-rewrites.ts`.
 *
 * Why codegen instead of reading the responses at seed time: the raw responses
 * live in `research/` (gitignored) and never leave this machine. Baking the
 * parsed data into a committed `.ts` lets the database be rebuilt on any machine
 * from the public repo alone (see the pipeline architecture: this Mac is the
 * engine, the other machine only consumes).
 *
 * Run:  pnpm cues:import      (then `pnpm db:push` once, and `pnpm db:seed`)
 *
 * Strict block format (per exercise), as requested by cue-rewrite-prompts.ts:
 *
 *   ### <slug> · <Exercise Name>
 *   - **internal** · <cue text>
 *   - **external** · <cue text>
 *   - **external** · <cue text>
 *   - **tactile**  · <cue text>
 *   - _citation: <Author Year, Journal, PMID/DOI>_
 *
 * The parser is deliberately tolerant of separator/markdown variations, since
 * the responses are produced by a language model, not a machine.
 */

import { prisma } from "../src/lib/prisma";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const RESEARCH_DIR = join(process.cwd(), "research");
const OUT_FILE = join(
  process.cwd(),
  "prisma",
  "seed",
  "extensions",
  "cue-rewrites.ts",
);

const VALID_FOCUS = new Set(["internal", "external", "tactile", "imagery"]);

// Attentional focus (Wulf) → existing delivery-modality cueType, so the current
// UI label (which renders cueType) keeps working without changes.
const FOCUS_TO_CUE_TYPE: Record<string, string> = {
  internal: "verbal",
  external: "verbal",
  tactile: "tactile",
  imagery: "visual",
};

interface ParsedCue {
  text: string;
  focus: string;
  cueType: string;
}

interface CueRewrite {
  slug: string;
  citation: string | null;
  cues: ParsedCue[];
}

// Separator chars that may sit between the focus tag and the cue text, or
// between slug and name: middle dot, bullet, en/em dash, hyphen, colon, pipe.
const SEP = "[·•:\\-–—|]";

const HEADER_RE = new RegExp(
  `^#{1,6}\\s+\`?([a-z0-9][a-z0-9-]*)\`?\\s*(?:${SEP}\\s*(.*))?$`,
);
const CUE_RE = new RegExp(
  `^[-*]\\s*\\*{0,2}\\s*(internal|external|tactile|imagery)\\s*\\*{0,2}\\s*${SEP}?\\s*(.+?)\\s*$`,
  "i",
);
const CITATION_RE = /citation\s*[:·•\-–—]?\s*(.+?)[_*\s]*$/i;

/** Strip surrounding markdown emphasis and code fences from a cue line's text. */
function cleanText(raw: string): string {
  return raw
    .replace(/^[*_`]+/, "")
    .replace(/[*_`]+$/, "")
    .trim();
}

function parseResponse(content: string): CueRewrite[] {
  const lines = content.split(/\r?\n/);
  const blocks: CueRewrite[] = [];
  let current: CueRewrite | null = null;

  for (let raw of lines) {
    const line = raw.replace(/^```.*$/, "").trim(); // drop code-fence lines
    if (!line) continue;

    const header = HEADER_RE.exec(line);
    if (header) {
      if (current && current.cues.length) blocks.push(current);
      current = { slug: header[1], citation: null, cues: [] };
      continue;
    }
    if (!current) continue;

    const cue = CUE_RE.exec(line);
    if (cue) {
      const focus = cue[1].toLowerCase();
      const text = cleanText(cue[2]);
      if (VALID_FOCUS.has(focus) && text) {
        current.cues.push({ text, focus, cueType: FOCUS_TO_CUE_TYPE[focus] });
      }
      continue;
    }

    if (/citation/i.test(line)) {
      const m = CITATION_RE.exec(line);
      if (m) current.citation = cleanText(m[1]) || null;
    }
  }
  if (current && current.cues.length) blocks.push(current);
  return blocks;
}

function codegen(rewrites: CueRewrite[]): string {
  // Stable order so the generated file diffs cleanly across runs.
  const sorted = [...rewrites].sort((a, b) => a.slug.localeCompare(b.slug));
  const data = JSON.stringify(sorted, null, 2);

  return `// AUTO-GENERATED by scripts/import-cue-rewrites.ts — do not edit by hand.
// Regenerate with: pnpm cues:import
// Source: literature-review cue-rewrite responses (research/, gitignored).
import { prisma, logSection, logCount } from "../client";

interface CueRewrite {
  slug: string;
  citation: string | null;
  cues: { text: string; focus: string; cueType: string }[];
}

const REWRITES: CueRewrite[] = ${data};

/**
 * Replace each listed exercise's cues with its evidence-based, focus-classified
 * set. Idempotent: clears existing cues for the exercise, then writes the new
 * ones. Runs last in the seed so it overrides cues created by earlier steps.
 */
export async function seedCueRewritesExtension() {
  logSection("Coaching-cue rewrites (evidence-based)");
  let applied = 0;
  let missing = 0;

  for (const r of REWRITES) {
    const ex = await prisma.exercise.findUnique({
      where: { slug: r.slug },
      select: { id: true },
    });
    if (!ex) {
      console.warn(\`    ⚠ skip — unknown exercise slug: \${r.slug}\`);
      missing++;
      continue;
    }
    await prisma.cue.deleteMany({ where: { exerciseId: ex.id } });
    await prisma.cue.createMany({
      data: r.cues.map((c, i) => ({
        exerciseId: ex.id,
        text: c.text,
        focus: c.focus,
        cueType: c.cueType,
        citation: r.citation,
        order: i,
      })),
    });
    applied++;
  }

  logCount("exercises re-cued", applied);
  if (missing) logCount("skipped (unknown slug)", missing);
}
`;
}

async function main() {
  console.log("📥 Importing coaching-cue rewrites from research responses...\n");

  let files: string[] = [];
  try {
    files = readdirSync(RESEARCH_DIR).filter(
      (f) => /^cues-batch-.*-response\.md$/.test(f),
    );
  } catch {
    console.log(`No research/ directory found — generating empty extension.`);
  }

  const allRewrites: CueRewrite[] = [];
  for (const f of files) {
    const parsed = parseResponse(readFileSync(join(RESEARCH_DIR, f), "utf8"));
    console.log(`   ${f}: parsed ${parsed.length} exercise block(s)`);
    allRewrites.push(...parsed);
  }

  // Validate slugs against the live catalog; warn (don't drop) so the operator
  // sees typos. Unknown slugs still get written and are skipped at seed time.
  const known = new Set(
    (await prisma.exercise.findMany({ select: { slug: true } })).map(
      (e) => e.slug,
    ),
  );
  const unknown = allRewrites.filter((r) => !known.has(r.slug));
  const wrongCount = allRewrites.filter((r) => r.cues.length !== 4);
  const noCitation = allRewrites.filter((r) => !r.citation);

  // De-dup by slug — last occurrence wins (a later batch supersedes an earlier).
  const bySlug = new Map<string, CueRewrite>();
  for (const r of allRewrites) bySlug.set(r.slug, r);
  const rewrites = [...bySlug.values()];

  writeFileSync(OUT_FILE, codegen(rewrites));

  console.log(`\n✅ Generated ${OUT_FILE.replace(process.cwd() + "/", "")}`);
  console.log(`   Exercises with rewritten cues: ${rewrites.length}`);
  if (wrongCount.length) {
    console.log(`\n⚠  ${wrongCount.length} block(s) not exactly 4 cues (review the response):`);
    for (const r of wrongCount) console.log(`   - ${r.slug} (${r.cues.length} cues)`);
  }
  if (unknown.length) {
    console.log(`\n⚠  ${unknown.length} unknown slug(s) — fix typos or they'll be skipped at seed:`);
    for (const r of unknown) console.log(`   - ${r.slug}`);
  }
  if (noCitation.length) {
    console.log(`\n⚠  ${noCitation.length} block(s) missing a citation.`);
  }
  console.log(
    `\nNext: \`pnpm db:push\` (first time only, adds focus/citation columns), then \`pnpm db:seed\`.`,
  );
}

main()
  .then(async () => prisma.$disconnect())
  .catch(async (e) => {
    console.error("❌ Cue-rewrite import failed:", e);
    await prisma.$disconnect();
    process.exit(1);
  });
