#!/usr/bin/env tsx
/**
 * Import category + structured position data generated by the
 * categorize-and-positions workflow. Reads a JSON file of
 * { slug, category, startPosition, endPosition, rom } items and updates each
 * exercise. Only sets fields that are currently empty (won't clobber any
 * human-authored positions), except category which is always set.
 *
 * Usage: tsx scripts/import-categories-positions.ts <items.json> [--apply]
 */
import { PrismaClient } from "@prisma/client";
import { readFileSync } from "node:fs";

const FILE = process.argv[2];
const APPLY = process.argv.includes("--apply");
if (!FILE) throw new Error("usage: import-categories-positions.ts <items.json> [--apply]");
const p = new PrismaClient();

const CATEGORIES = new Set(["strength", "stretch", "mobility", "balance", "motor-control", "breathwork", "aerobic", "sensory", "functional"]);

async function main() {
  const items: any[] = JSON.parse(readFileSync(FILE, "utf8"));
  let cat = 0, pos = 0, missing = 0, badCat = 0;
  for (const it of items) {
    const ex = await p.exercise.findUnique({ where: { slug: it.slug }, select: { id: true, startPosition: true, endPosition: true, rom: true } });
    if (!ex) { missing++; continue; }
    const data: any = {};
    if (it.category && CATEGORIES.has(it.category)) { data.category = it.category; cat++; } else if (it.category) badCat++;
    if (it.startPosition && !ex.startPosition) data.startPosition = it.startPosition;
    if (it.endPosition && !ex.endPosition) data.endPosition = it.endPosition;
    if (it.rom && !ex.rom) data.rom = it.rom;
    if (data.startPosition || data.endPosition || data.rom) pos++;
    if (APPLY && Object.keys(data).length) await p.exercise.update({ where: { id: ex.id }, data });
  }
  console.log(APPLY ? "APPLIED" : "DRY RUN (pass --apply)");
  console.log(`  items: ${items.length} | categories set: ${cat} | positions filled: ${pos} | slug not found: ${missing} | invalid category: ${badCat}`);
}

main().finally(() => p.$disconnect());
